### ISSUE TITLE
Clarifications on src.angle

### ISSUE THREAD

**Issue by jclark** [facebookincubator/Glean#39]
I am trying to understand Glean's requirements for representing source locations. There are a couple of points that are not clear to me after reading src.angle:

1. What's a column? Is it
    * a visual concept (based on the display column), which would take into account expansion of tabs and Unicode combining characters, or
    * an offset into the string content of the line, in which case is the offset counted in UTF-8 bytes, UTF-16 code units, or code points?
2. How do byte spans work if a file uses \r\n as a line terminator? Do they assume \r\n has been normalized into \n or are they counted as two bytes?

**Comment by zsol** [comment]
Great questions, we should clarify these in the src.angle as comments.
Columns are a visual concept, so Unicode combining characters are taken into account (just like in an editor).
Byte offsets don't assume any conversion of the source code, so CRLF is two bytes

**Comment by lazamar** [comment]
Please note that tab expansion is editor-specific and is not accounted for.

**Comment by lazamar** [comment]
As a clarification, I believe @zsol meant here that Unicode code points spanning multiple bytes occupy a single column.
We don't currently handle Unicode combining characters per se, we count each code point as a single column.

**Comment by lazamar** [comment]
The clarification was added to the code in 2025f6d
