### ISSUE TITLE
Are there any plans to release a Haskell indexer?

### ISSUE THREAD

**Issue by chrislf** [facebookincubator/Glean#43]
The readme doesn't mention a Haskell indexer: is this planned or likely? Thanks!

**Comment by simonmar** [comment]
It's likely at some point. I think we're looking at indexing based on the contents of HIE files. @pepeiborra might know more.

**Comment by pepeiborra** [comment]
@gustavoavena has written a semi-complete glean indexer that consumes a hiedb:

> HIE files -> hiedb -> glean

Would that be useful for you?

**Comment by chrislf** [comment]
That sounds great! Happy to close this and wait for that to be released. Thanks!
