### ISSUE TITLE
Motivation: Document what kinds of facts you'd analyze.

### ISSUE THREAD

**Issue by JeffreyBenjaminBrown** [facebookincubator/Glean#44]
The introductory documentation says that Glean is for analyzing "facts about source code", but does not give examples of those facts. Front-loading the introduction with examples of =questions it can usefully answer would help motivate a user. (I dug ten pages into the documentation, still don't know why I'd use it, and have lost interest.)

**Comment by simonmar** [comment]
Does this help? https://github.com/facebookincubator/Glean/commit/d4c84848326f83b4f30c2c98cb4bc5a4c1eee9a2

https://glean.software/docs/introduction/

**Comment by JeffreyBenjaminBrown** [comment]
Yes, that's what I was looking for. Thanks, Simon!
