### ISSUE TITLE
glean throws error on basic usage with haskell-hie indexer

### ISSUE THREAD

**Issue by Boarders** [facebookincubator/Glean#457]
I am trying to use the `haskell-hie` indexer. I have a local build of `glean` and if I do:
```
../github/Glean-copy/dist-newstyle/build/x86_64-linux/ghc-8.10.2/glean-0.1.0.0/x/glean/build/glean/glean index --db temp-db/ haskell-hie dist-newstyle/
```
in a local project, then I get the following error:
```
glean: basic-thriftservice does not support Tier
CallStack (from HasCallStack):
  error, called at glean/util/Glean/Impl/ThriftService.hs:98:25 in glean-0.1.0.0-inplace-util:Glean.Impl.ThriftService
  ```
  
  Any ideas what I might be doing wrong?

**Comment by simonmar** [comment]
The error means you didn't use either `--db-root` to use local DBs or `--service` to connect to a Glean server. The error message is terrible and we need to do something about it.
